/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideClassify: typeof import('./src/components/aside-cpns/aside-classify.vue')['default']
    AsideLabels: typeof import('./src/components/aside-cpns/aside-labels.vue')['default']
    AsideRecommand: typeof import('./src/components/aside-cpns/aside-recommand.vue')['default']
    AsideXinji: typeof import('./src/components/aside-cpns/aside-xinji.vue')['default']
    CommentForm: typeof import('./src/components/comment-form.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ListItem: typeof import('./src/components/list-item.vue')['default']
    MainAside: typeof import('./src/components/main-aside.vue')['default']
    MainFooter: typeof import('./src/components/main-footer.vue')['default']
    MainHeader: typeof import('./src/components/main-header.vue')['default']
    MessageForm: typeof import('./src/components/message-form.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchVal: typeof import('./src/components/search-val.vue')['default']
    TimeLine: typeof import('./src/components/time-line.vue')['default']
    WordList: typeof import('./src/components/word-list.vue')['default']
  }
}
